# Properties file for integration tests
# Overrides application.yml default properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fresh?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false
#    host: localhost:3306
#    db: fresh?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASS}
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      sql: debug
      ddl-auto: none # create-drop para crear las entidades, una vez creadas y finalizado el mododel cambiar a none
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8082 # no cambiar en prod