# Properties file for local/dev environment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties
spring:
  datasource:
    host: localhost:3306
    db: fresh?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASS}
    initialization-mode: always
    platform: mysql

  jpa:
    show-sql: true
    hibernate:
      sql: debug
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8082 # do not change in prod
