# Properties file for integration tests
# Overrides application.yml default properties

#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    host: localhost:9092
#    db: testdb
#    username: ${LOCAL_DB_USER}
##    sa
#    password: ${LOCAL_DB_PASS}
##   empty
#    initialization-mode: always
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    show-sql: true
#    hibernate:
#      sql: debug
#      ddl-auto: none # create-drop para crear las entidades, una vez creadas y finalizado el mododel cambiar a none
#    database-platform: org.hibernate.dialect.H2Dialect
#
#server:
#  port: 8082 # no cambiar en prod
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    platform: h2
#    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create